### ISSUE TITLE
Error data from IMGT running Retrieve Template 

### ISSUE THREAD

**Issue by mickael-decastro** [matdoering/openPrimeR#11]
Hello, 

I deployed openPrimeR in docker following the Readme and docker image on docker hub.  When I check Third-party tools status I have selenium-python in unvailable state. To fix it I installed manually python 2.7, pip and module selenium. After that everything is ok on this part. 

When I run Retrieve Template on "Mus musculus" I receive the following message on GUI. 
```
IMGT Data Unavailable
It was not possible to retrieve the selected data from IMGT. Possible reasons could be having no internet connection or missing dependencies (selenium for python).
```

And on docker container log 

```
Warning in openPrimeRui:::retrieve.IMGT.templates(input$IMGT_DB_species,  :
  Failed to retrieve templates from IMGT for unknown reason.
/usr/local/lib/python2.7/dist-packages/selenium/webdriver/phantomjs/webdriver.py:49: UserWarning: Selenium support for PhantomJS has been deprecated, please use headless versions of Chrome or Firefox instead
  warnings.warn('Selenium support for PhantomJS has been deprecated, please use headless '
Traceback (most recent call last):
  File "/usr/local/lib/R/site-library/openPrimeRui/shiny/shiny_server/extra_IMGT_template_set_extractor.py", line 104, in <module>
    set_option(driver, field, value)
  File "/usr/local/lib/R/site-library/openPrimeRui/shiny/shiny_server/extra_IMGT_template_set_extractor.py", line 44, in set_option
    element = Select(driver.find_element_by_name(field))
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 496, in find_element_by_name
    return self.find_element(by=By.NAME, value=name)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: {"errorMessage":"Unable to find element with name 'model.subgroup'","request":{"headers":{"Accept":"application/json","Accept-Encoding":"identity","Content-Length":"97","Content-Type":"application/json;charset=UTF-8","Host":"127.0.0.1:34687","User-Agent":"selenium/3.141.0 (python linux)"},"httpVersion":"1.1","method":"POST","post":"{\"using\": \"name\", \"sessionId\": \"80b91d40-7d7e-11ed-861b-b1bd0a075e2a\", \"value\": \"model.subgroup\"}","url":"/element","urlParsed":{"anchor":"","query":"","file":"element","directory":"/","path":"/element","relative":"/element","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/element","queryKey":{},"chunks":["element"]},"urlOriginal":"/session/80b91d40-7d7e-11ed-861b-b1bd0a075e2a/element"}}
Screenshot: available via screen
Warning in openPrimeRui:::retrieve.IMGT.templates(input$IMGT_DB_species,  :
  Failed to retrieve templates from IMGT for unknown reason.
```
Can you help me ? 

thanks

**Comment by matdoering** [comment]
Looks like the parser for the IMGT data doesn't work anymore. I'd recommend to just download the data from IMGT directly.
